import { Container, Flex, Stack } from "@chakra-ui/react";
import Nav from "./Nav";
import Head from "next/head";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <Container maxW="container.xl">{children}</Container>
    </>
  );
};

export default Layout;
